
const P=[["Volkovson",1342,"Manchester United"],["Osetskyi_3",1287,"Real Madrid"],["Romeo_130901",1254,"Arsenal"],["Mitsuki_one_love",1198,"Barcelona"],["Loter24",1162,"Milan"],["vladiks56",1084,"Chelsea"]];
const C={"Manchester United":"🔴","Real Madrid":"⚪","Arsenal":"🔴","Barcelona":"🔵","Milan":"⚫","Chelsea":"🔵"};
let route="home",tab="mine",hist="cup"; let testParticipants=[]; const A=document.querySelector("#app");
const pc=n=>`<div class="pcard">${n}</div>`, cr=c=>`<div class="crest">${C[c]||"⚽"}</div>`;
function go(r){route=r;tab="mine";draw()} window.go=go;
function tabs(a){return `<div class=tabs>${a.map(x=>`<button class="${tab==x[0]?"on":""}" onclick="tab='${x[0]}';draw()">${x[1]}</button>`).join("")}</div>`}
function home(){return `<div class=winner>${pc("Volkovson")}<div><div class=gold>🏆 ОСТАННІЙ ПЕРЕМОЖЕЦЬ</div><h2>VOLKOVSON</h2><div>CENTURIA CUP #3</div><div class=muted>26.09.2026</div></div><div>${cr("Manchester United")}<div class="center muted">Manchester United</div></div></div><div class=grid><button class="tile big" onclick="go('league')"><strong>🏆 ЛІГА</strong><span class=muted>Таблиця та тури</span></button><button class="tile big" onclick="go('cup')"><strong>🏆 КУБОК</strong><span class=muted>Турнірна сітка</span></button><button class=tile onclick="go('friendly')"><strong>⚔️ ТОВАРИСЬКИЙ МАТЧ</strong><span class=muted>Створити виклик</span></button><button class=tile onclick="go('evo')"><strong>🔥 EVO</strong><span class=muted>#1 Volkovson • 1342</span></button><button class=tile onclick="go('history')"><strong>🕘 ІСТОРІЯ</strong></button><button class=tile onclick="go('players')"><strong>👥 ГРАВЦІ</strong></button><button class="tile admin-test" onclick="go('test')"><strong>🧪 ТЕСТ ADMIN</strong><span class=muted>Ручні учасники League / Cup</span></button></div>`}
function league(){let body=tab=="mine"?`<div class=card><div class=gold>НАСТУПНИЙ МАТЧ • ТУР 4</div><div class=match><div><h3>Osetskyi_3</h3><span class=muted>Real Madrid</span></div><div class=score>VS</div><div class=right><h3>Volkovson</h3><span class=muted>Manchester United</span></div></div><button class=primary onclick=modalResult()>ВНЕСТИ РЕЗУЛЬТАТ</button></div>`:tab=="round"?["Volkovson 3 : 1 Romeo_130901 ✓","Osetskyi_3 2 : 2 Mitsuki_one_love ✓","Loter24 — : — vladiks56 ⏳"].map(x=>`<div class=card>${x}</div>`).join(""):tab=="table"?`<div class=card><table class=table><tr><th>#</th><th>Гравець</th><th>І</th><th>РГ</th><th>О</th></tr>${P.slice(0,5).map((p,i)=>`<tr><td>${i+1}</td><td>${C[p[2]]} ${p[0]}</td><td>4</td><td>${[8,5,3,0,-2][i]}</td><td><b>${[10,9,7,5,4][i]}</b></td></tr>`).join("")}</table></div>`:[1,2,3,4,5,6,7].map(i=>`<div class=card><b>ТУР ${i}</b><span style=float:right>${i<4?"✓ Завершено":i==4?"🟢 Поточний":"🔒"}</span></div>`).join("");return `<h2>CENTURIA LEAGUE #1</h2><p class=gold>ОДНЕ КОЛО • ТУР 4/7</p>${tabs([["mine","МОЇ МАТЧІ"],["round","ТУР"],["table","ТАБЛИЦЯ"],["calendar","КАЛЕНДАР"]])}${body}`}
function cup(){let body=tab=="mine"?`<div class="card center"><div class=gold>1/2 ФІНАЛУ • BO3</div><h2>OSETSKYI_3</h2><p>Real Madrid</p><div class=score>VS</div><h2>VOLKOVSON</h2><p>Manchester United</p><button class=primary onclick=modalResult()>ВНЕСТИ РЕЗУЛЬТАТ</button></div>`:tab=="bracket"?`<div class=card><h3>1/4 → 1/2 → ФІНАЛ</h3><p>Volkovson <b>3:1</b> Romeo_130901</p><p>Osetskyi_3 <b>2:0</b> Mitsuki_one_love</p><hr><p>Volkovson <b>—:—</b> Osetskyi_3</p><p>Loter24 <b>—:—</b> vladiks56</p></div>`:tab=="round"?`<div class=card>ПІВФІНАЛ • Volkovson — : — Osetskyi_3</div><div class=card>ПІВФІНАЛ • Loter24 — : — vladiks56</div>`:`<div class=card>1/4 • Volkovson 3:1 Romeo_130901</div>`;return `<h2>CENTURIA CUP #1</h2>${tabs([["mine","МІЙ МАТЧ"],["bracket","СІТКА"],["round","РАУНД"],["old","ІСТОРІЯ"]])}${body}`}
function friendly(){let all=[["Osetskyi_3","Manchester United",3,"Volkovson","Milan",2],["Romeo_130901","Arsenal",1,"Mitsuki_one_love","Barcelona",1],["Osetskyi_3","Real Madrid",null,"Romeo_130901","Arsenal",null]];let list=tab=="all"?all:all.filter(x=>x[0]=="Osetskyi_3"||x[3]=="Osetskyi_3");return `<div class=actions><h2 style="flex:1">ТОВАРИСЬКІ</h2><button class=primary onclick=modalMatch()>＋ СТВОРИТИ МАТЧ</button></div>${tabs([["mine","МОЇ МАТЧІ"],["all","УСІ МАТЧІ"]])}${list.map(x=>`<div class="card match"><div>${C[x[1]]||"⚽"} <b>${x[0]}</b><div class=muted>${x[1]}</div></div><div class=score>${x[2]==null?"VS":x[2]+" : "+x[5]}</div><div class=right><b>${x[3]}</b> ${C[x[4]]||"⚽"}<div class=muted>${x[4]}</div></div></div>`).join("")}`}
function evo(){let q=[...P].sort((a,b)=>b[1]-a[1]);return `<h2>🔥 CENTURIA EVO</h2><p class=muted>Старт 1000 • Elo K=32 • мінімум 100</p>${q.map((p,i)=>`<div class=card><b>${i<3?["🥇","🥈","🥉"][i]:i+1+"."} ${p[0]}</b><span class=gold style=float:right;font-size:20px>${p[1]} EVO</span></div>`).join("")}`}
function players(){return `<h2>ГРАВЦІ ARENA</h2><div class=players>${P.map((p,i)=>`<div class="card pitem">${pc(p[0])}<div><b>${p[0]}</b><div class=gold>🔥 ${p[1]} EVO • #${i+1}</div><div class=muted>❤️ ${p[2]}</div></div>${cr(p[2])}</div>`).join("")}</div>`}
function history(){let data=hist=="cup"?[["Volkovson","26.09.2026","CENTURIA CUP #3","Manchester United"],["Romeo_130901","28.08.2026","CENTURIA CUP #2","Arsenal"]]:[["Osetskyi_3","12.09.2026","CENTURIA LEAGUE #2","Real Madrid"]];return `<h2>ІСТОРІЯ</h2><div class=tabs><button class="${hist=="cup"?"on":""}" onclick="hist='cup';draw()">КУБОК</button><button class="${hist=="league"?"on":""}" onclick="hist='league';draw()">ЛІГА</button></div>${data.map(x=>`<div class="card history">${pc(x[0])}<div class=center><h3>${x[0]}</h3><div>${x[1]}</div><div class=gold>${x[2]}</div></div><div>${cr(x[3])}<div class="center muted">${x[3]}</div></div></div>`).join("")}`}

function test(){return `<h2>🧪 ТЕСТОВИЙ РЕЖИМ ADMIN</h2><p class=muted>Локальний режим для перевірки Arena. Учасників можна додати вручну без голосування.</p><div class=card><h3>УЧАСНИКИ ТЕСТУ</h3>${P.map(p=>`<label style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid #ffffff12"><input type=checkbox ${testParticipants.includes(p[0])?'checked':''} onchange="toggleTest('${p[0]}')"><b>${p[0]}</b><span class=muted style="margin-left:auto">${p[1]} EVO</span></label>`).join('')}<div class=actions style="margin-top:14px"><button class=primary onclick="seedTest('league')">СТВОРИТИ TEST LEAGUE</button><button class=primary onclick="seedTest('cup')">СТВОРИТИ TEST CUP</button></div><button onclick="testParticipants=[];draw()">ОЧИСТИТИ ТЕСТ</button></div><div class=card><b>Обрано: ${testParticipants.length}</b><p class=muted>${testParticipants.join(', ')||'Ще нікого не додано'}</p></div>`}
function toggleTest(n){testParticipants.includes(n)?testParticipants=testParticipants.filter(x=>x!==n):testParticipants.push(n);draw()} window.toggleTest=toggleTest;
function seedTest(kind){if(testParticipants.length<2){alert('Додай мінімум 2 учасників');return} alert((kind==='league'?'Test League':'Test Cup')+' створено для '+testParticipants.length+' учасників. Це локальна демо-перевірка.')} window.seedTest=seedTest;

function modalMatch(){document.body.insertAdjacentHTML("beforeend",`<div class=modal onclick="if(event.target==this)this.remove()"><div><h2>НОВИЙ МАТЧ</h2><label>Мій клуб</label><input value="Manchester United"><label>Суперник онлайн</label><select><option>Volkovson 🟢</option><option>Romeo_130901 🟢</option><option>Mitsuki_one_love 🟢</option></select><button class=primary onclick="this.closest('.modal').remove()">НАДІСЛАТИ ВИКЛИК</button></div></div>`)}
function modalResult(){document.body.insertAdjacentHTML("beforeend",`<div class=modal onclick="if(event.target==this)this.remove()"><div><h2>ВНЕСТИ РЕЗУЛЬТАТ</h2><input type=number value=3><input type=number value=2><p class=muted>EVO зміниться після підтвердження суперником.</p><button class=primary onclick="this.closest('.modal').remove()">НАДІСЛАТИ</button></div></div>`)}
function draw(){let f={home,league,cup,friendly,evo,players,history,test}[route];A.innerHTML=f()} draw();
